/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface IComptrollerContract
  extends Truffle.Contract<IComptrollerInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<IComptrollerInstance>;
}

type AllEvents = never;

export interface IComptrollerInstance extends Truffle.ContractInstance {
  claimComp: {
    (holder: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(holder: string, txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(
      holder: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      holder: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  getCompAddress(txDetails?: Truffle.TransactionDetails): Promise<string>;

  methods: {
    claimComp: {
      (holder: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        holder: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        holder: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        holder: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    getCompAddress(txDetails?: Truffle.TransactionDetails): Promise<string>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
