/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface ICurveFiRewardsSbtcContract
  extends Truffle.Contract<ICurveFiRewardsSbtcInstance> {
  "new"(
    meta?: Truffle.TransactionDetails
  ): Promise<ICurveFiRewardsSbtcInstance>;
}

type AllEvents = never;

export interface ICurveFiRewardsSbtcInstance extends Truffle.ContractInstance {
  rewardsToken(txDetails?: Truffle.TransactionDetails): Promise<string>;

  methods: {
    rewardsToken(txDetails?: Truffle.TransactionDetails): Promise<string>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
