/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

/// <reference types="truffle-typings" />

import * as TruffleContracts from ".";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "AccessModule"): TruffleContracts.AccessModuleContract;
      require(name: "Base"): TruffleContracts.BaseContract;
      require(
        name: "CompoundProtocol_DAI"
      ): TruffleContracts.CompoundProtocol_DAIContract;
      require(
        name: "CompoundProtocol"
      ): TruffleContracts.CompoundProtocolContract;
      require(name: "Context"): TruffleContracts.ContextContract;
      require(name: "CoreInterface"): TruffleContracts.CoreInterfaceContract;
      require(
        name: "CurveFiYProtocol"
      ): TruffleContracts.CurveFiYProtocolContract;
      require(name: "DCAModule"): TruffleContracts.DCAModuleContract;
      require(
        name: "DCAOperatorRole"
      ): TruffleContracts.DCAOperatorRoleContract;
      require(
        name: "DefiOperatorRole"
      ): TruffleContracts.DefiOperatorRoleContract;
      require(
        name: "DistributionToken"
      ): TruffleContracts.DistributionTokenContract;
      require(name: "ERC165"): TruffleContracts.ERC165Contract;
      require(name: "ERC20"): TruffleContracts.ERC20Contract;
      require(name: "ERC20Burnable"): TruffleContracts.ERC20BurnableContract;
      require(name: "ERC20Detailed"): TruffleContracts.ERC20DetailedContract;
      require(name: "ERC20Mintable"): TruffleContracts.ERC20MintableContract;
      require(name: "ERC721"): TruffleContracts.ERC721Contract;
      require(name: "ERC721Burnable"): TruffleContracts.ERC721BurnableContract;
      require(
        name: "ERC721Enumerable"
      ): TruffleContracts.ERC721EnumerableContract;
      require(name: "ERC721Full"): TruffleContracts.ERC721FullContract;
      require(name: "ERC721Metadata"): TruffleContracts.ERC721MetadataContract;
      require(
        name: "FakeUniswapRouter"
      ): TruffleContracts.FakeUniswapRouterContract;
      require(name: "IAccessModule"): TruffleContracts.IAccessModuleContract;
      require(name: "ICErc20"): TruffleContracts.ICErc20Contract;
      require(name: "IComptroller"): TruffleContracts.IComptrollerContract;
      require(
        name: "ICurveFiDeposit"
      ): TruffleContracts.ICurveFiDepositContract;
      require(name: "ICurveFiSwap"): TruffleContracts.ICurveFiSwapContract;
      require(name: "IDefiProtocol"): TruffleContracts.IDefiProtocolContract;
      require(name: "IERC165"): TruffleContracts.IERC165Contract;
      require(name: "IERC20"): TruffleContracts.IERC20Contract;
      require(name: "IERC721"): TruffleContracts.IERC721Contract;
      require(
        name: "IERC721Enumerable"
      ): TruffleContracts.IERC721EnumerableContract;
      require(
        name: "IERC721Metadata"
      ): TruffleContracts.IERC721MetadataContract;
      require(
        name: "IERC721Receiver"
      ): TruffleContracts.IERC721ReceiverContract;
      require(
        name: "IPoolTokenBalanceChangeRecipient"
      ): TruffleContracts.IPoolTokenBalanceChangeRecipientContract;
      require(
        name: "IRAYNAVCalculator"
      ): TruffleContracts.IRAYNAVCalculatorContract;
      require(
        name: "IRAYPortfolioManager"
      ): TruffleContracts.IRAYPortfolioManagerContract;
      require(name: "IRAYStorage"): TruffleContracts.IRAYStorageContract;
      require(name: "ISavingsModule"): TruffleContracts.ISavingsModuleContract;
      require(
        name: "IUniswapV2Router02"
      ): TruffleContracts.IUniswapV2Router02Contract;
      require(name: "IYErc20"): TruffleContracts.IYErc20Contract;
      require(name: "MinterRole"): TruffleContracts.MinterRoleContract;
      require(name: "Module"): TruffleContracts.ModuleContract;
      require(name: "Ownable"): TruffleContracts.OwnableContract;
      require(name: "Pausable"): TruffleContracts.PausableContract;
      require(name: "PauserRole"): TruffleContracts.PauserRoleContract;
      require(name: "Pool"): TruffleContracts.PoolContract;
      require(
        name: "PoolToken_Compound_DAI"
      ): TruffleContracts.PoolToken_Compound_DAIContract;
      require(
        name: "PoolToken_CurveFiY"
      ): TruffleContracts.PoolToken_CurveFiYContract;
      require(name: "PoolToken"): TruffleContracts.PoolTokenContract;
      require(name: "RAYProtocol"): TruffleContracts.RAYProtocolContract;
      require(
        name: "RewardDistributions"
      ): TruffleContracts.RewardDistributionsContract;
      require(name: "SavingsModule"): TruffleContracts.SavingsModuleContract;
      require(
        name: "WhitelistAdminRole"
      ): TruffleContracts.WhitelistAdminRoleContract;
      require(
        name: "WhitelistedRole"
      ): TruffleContracts.WhitelistedRoleContract;
    }
  }
}
